### PR TITLE
feat: 顶部操作栏自适应换行

### PR DESCRIPTION
**Pull request by Aybrea**
使顶部操作栏左侧按钮随宽度变化而换行展示

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/cherry-markdown?pullRequest=991) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/cherry-markdown?pullRequest=991) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/cherry-markdown?pullRequest=991) it.</sub>

**Comment by sunsonliu** [comment]
感谢贡献~LGTM

**Comment by sunsonliu** [comment]
image
https://tencent.github.io/cherry-markdown/examples/basic.html

发现个小问题，当没有右侧工具栏的时候，工具栏的整体高度被拉高了，是不是对 .toolbar-right 增加 min-height: 0; 就好了

**Comment by Aybrea** [comment]
> image https://tencent.github.io/cherry-markdown/examples/basic.html
> 
> 发现个小问题，当没有右侧工具栏的时候，工具栏的整体高度被拉高了，是不是对 .toolbar-right 增加 min-height: 0; 就好了

感觉可以

**Pull request merged**
